version: "3.8"

services:
  database:
    image: postgres:15-alpine
    container_name: database
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./api/data/schema.sql:/docker-entrypoint-initdb.d/base.sql
      - ./api/data/inserts.sql:/docker-entrypoint-initdb.d/insert.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bedev
    restart: always
    ports:
      - "5441:5432"
    networks:
      - bridge

  api:
    container_name: api
    ports:
      - "8080:8080"
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/bedev
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    networks:
      - bridge
    depends_on:
      - database

  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    command: npm start
    networks:
      - bridge
    depends_on:
      - api

networks:
  bridge:

volumes:
  postgres-data:
